### ISSUE TITLE
UIWebView in MatrixKit Pod is deprecated and will not be accepted by App Store in Future.

### ISSUE THREAD

**Issue by harsh1729** [matrix-org/matrix-ios-kit#636]
Hi, I am using MatrixKit in my project.
When I try to upload my app to AppStore, I get an error "Apple will stop accepting submissions of apps that use UIWebView APIs".

I found MatrixKit uses 'UIWebView'. Would we get a pod update where deprecated UIWebView is replaced?

**Comment by tladesignz** [comment]
Same here. This library needs to get rid of `UIWebView` or we need to get rid of `MatrixKit`...

**Comment by tladesignz** [comment]
BTW: There seem to be plans for `AFNetworking` to do just that, too:
https://github.com/AFNetworking/AFNetworking/pull/4430#issuecomment-544321511
(`MatrixSDK` depends on it...)

**Comment by samnoyes** [comment]
I need this to be fixed in order to distribute my app on TestFlight. There's almost no support on this library.

**Comment by tladesignz** [comment]
We ended up stripping it down to what we need, which wasn’t much, anyway, and finally depart from this mess, which also had the upside of getting rid of all the warnings this lib throws.
